name: Deploy to GitHub Pages

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install dependencies (if any)
      run: |
        if [ -f package.json ]; then
          npm ci
        else
          echo "No package.json found, skipping dependency installation"
        fi

    - name: Check file structure
      run: |
        echo "Project structure:"
        ls -la
        echo "CSS files:"
        ls -la css/
        echo "JS files:"
        ls -la js/

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        cname: finance-u.netlify.app  # Optional: replace with your custom domain

    - name: Comment on PR with preview link
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `🚀 **Preview deployment ready!**\n\nYour changes have been deployed to a preview environment. You can view them at: https://finance-u-preview.netlify.app\n\nThe preview will be available for the next 24 hours.`
          })

